/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 22/04/2021 10:19:48
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI14_VALUE                          14000000
#define MX_HSI48_VALUE                          48000000
#define MX_PLLCLKFreq_Value                     16000000
#define MX_PLLMCOFreq_Value                     16000000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       8000000
#define MX_MCOFreq_Value                        16000000
#define MX_FCLKCortexFreq_Value                 8000000
#define MX_TimSysFreq_Value                     8000000
#define MX_AHBFreq_Value                        8000000
#define MX_APB1Freq_Value                       500000
#define MX_APB1TimFreq_Value                    1000000
#define MX_ADCoutputFreq_Value                  14000000
#define MX_FLITFCLKFreq_Value                   8000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       8000000
#define MX_I2SFreq_Value                        16000000
#define MX_USART1Freq_Value                     500000
#define MX_USART2Freq_Value                     8000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_WatchDogFreq_Value                   40000
#define MX_VCOOutput2Freq_Value                 8000000

/*-------------------------------- DAC        --------------------------------*/

#define MX_DAC                                  1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_COMP_DAC1_group_Pin_Remapping        __NULL
#define MX_COMP_DAC1_group_Pin                  PA4
#define MX_COMP_DAC1_group_GPIOx                GPIOA
#define MX_COMP_DAC1_group_GPIO_PuPd            GPIO_NOPULL
#define MX_COMP_DAC1_group_GPIO_Pin             GPIO_PIN_4
#define MX_COMP_DAC1_group_GPIO_Mode            GPIO_MODE_ANALOG

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB8 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SCL_Pin_Remapping               __NULL
#define MX_I2C1_SCL_Pin                         PB8
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_8
#define MX_I2C1_SCL_GPIO_FM8                    __NULL
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB9 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SDA_Pin_Remapping               __NULL
#define MX_I2C1_SDA_Pin                         PB9
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD
#define MX_I2C1_SDA_GPIO_FM9                    __NULL

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM16      --------------------------------*/

#define MX_TIM16                                1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM16_IRQn */
#define MX_TIM16_IRQn_interruptPremptionPriority 0
#define MX_TIM16_IRQn_Subriority                0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART2_TX_Pin_Remapping              __NULL
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF1_USART2

/* Pin PA3 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART2_RX_Pin_Remapping              __NULL
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF1_USART2

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 0
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin_Remapping                   __NULL
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_B1                                   PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PC12 */
#define MX_PC12_Pin_Remapping                   __NULL
#define MX_PC12_Pin                             PC12
#define MX_PC12_GPIOx                           GPIOC
#define MX_PC12_GPIO_PuPd                       GPIO_PULLUP
#define MX_Button1                              PC12
#define MX_PC12_GPIO_Pin                        GPIO_PIN_12
#define MX_PC12_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PB4 */
#define MX_PB4_Pin_Remapping                    __NULL
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin_Remapping                    __NULL
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LD2                                  PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA8 */
#define MX_PA8_Pin_Remapping                    __NULL
#define MX_PA8_Pin                              PA8
#define MX_PA8_GPIOx                            GPIOA
#define MX_PA8_GPIO_PuPd                        GPIO_NOPULL
#define MX_RE_OUTA                              PA8
#define MX_PA8_GPIO_Pin                         GPIO_PIN_8
#define MX_PA8_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PC11 */
#define MX_PC11_Pin_Remapping                   __NULL
#define MX_PC11_Pin                             PC11
#define MX_PC11_GPIOx                           GPIOC
#define MX_PC11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC11                                 PC11
#define MX_PC11_GPIO_Pin                        GPIO_PIN_11
#define MX_PC11_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PA9 */
#define MX_PA9_Pin_Remapping                    __NULL
#define MX_PA9_Pin                              PA9
#define MX_PA9_GPIOx                            GPIOA
#define MX_PA9_GPIO_PuPd                        GPIO_NOPULL
#define MX_RE_OUTB                              PA9
#define MX_PA9_GPIO_Pin                         GPIO_PIN_9
#define MX_PA9_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

#endif  /* __MX_DEVICE_H */
